In [2]:
import streamlit
import pandas as pd
import os

In [5]:

script_data = pd.read_excel('..\\Pages\\Data_Analysis\\Stock\\Script_Market_Cap.xlsx')
script_data

,Scrip,Company,Listed Share,Paid-up (Rs),Total Paid-up Capital (Rs),Market Capitalization (Rs),Sector
0,NMB,NMB Bank Limited,183667060.0,100.0,1.836671e+10,5.126148e+10,COMMERCIAL BANK
1,SBL,Siddhartha Bank Limited,140899802.0,100.0,1.408998e+10,5.169614e+10,COMMERCIAL BANK
2,KBL,Kumari Bank Limited,262258613.0,100.0,2.622586e+10,6.789875e+10,COMMERCIAL BANK
3,MBL,Machhapuchchhre Bank Limited,116213573.0,100.0,1.162136e+10,3.252818e+10,COMMERCIAL BANK
4,EBL,Everest Bank Limited,117679040.0,100.0,1.176790e+10,9.061286e+10,COMMERCIAL BANK
...,...,...,...,...,...,...,...
287,MKCL,Muktinath Krishi Company Limited,7000000.0,100.0,7.000000e+08,1.121400e+10,OTHERS
288,NWCL,Nepal Warehousing Company Limited,6875000.0,100.0,6.875000e+08,7.720625e+09,OTHERS
289,NRM,Nepal Republic Media Limited,9675000.0,100.0,9.675000e+08,5.022292e+09,OTHERS
290,STC,Salt Trading Corporation Limited,3207171.0,100.0,3.207171e+08,2.132769e+10,TRADING
291,BBC,Bishal Bazar Company Limited,500000.0,100.0,5.000000e+07,2.417000e+09,TRADING

In [6]:
script_data = script_data['Scrip'].unique()
script_data

array(['NMB', 'SBL', 'KBL', 'MBL', 'EBL', 'SBI', 'HBL', 'SCB', 'NABIL',
       'CZBIL', 'PCBL', 'ADBL', 'SANIMA', 'NBL', 'GBIME', 'NICA', 'PRVU',
       'NIMB', 'LSL', 'MDB', 'GBBL', 'JBBL', 'KRBL', 'NABBC', 'EDBL',
       'SADBL', 'MNBBL', 'CORBL', 'SINDU', 'SHINE', 'GRDBL', 'MLBL',
       'KSBBL', 'LBBL', 'SAPDBL', 'NFS', 'BFC', 'GFCL', 'PFL', 'SIFC',
       'CFCL', 'JFL', 'SFCL', 'CMB', 'GMFIL', 'ICFC', 'MPFL', 'PROFL',
       'MFIL', 'RLFL', 'GUFL', 'SHL', 'TRH', 'OHL', 'CGH', 'KDL', 'CITY',
       'NHPC', 'BPCL', 'CHCL', 'AHPC', 'SJCL', 'SHPC', 'RHPL', 'BARUN',
       'UPPER', 'MBJC', 'AKPL', 'API', 'MKJC', 'DORDI', 'TVCL', 'MHL',
       'DHPL', 'NYADI', 'NGPL', 'RADHI', 'KKHC', 'GHL', 'HURJA', 'UMHL',
       'AKJCL', 'UPCL', 'SPL', 'NHDL', 'SPDL', 'HPPL', 'CHL', 'SAHAS',
       'JOSHI', 'BHPL', 'MHNL', 'PMHPL', 'UNHPL', 'KPCL', 'PPCL', 'RHGCL',
       'HDHPC', 'MKHC', 'SSHL', 'RURU', 'USHEC', 'EHPL', 'USHL', 'GLH',
       'BHDC', 'RFPL', 'BNHC', 'TAMOR', 'SHEL', 'SPHL', 'MEN', 'BEDC',
       'TSHL', 'LEC', 'UMRH', 'UHEWA', 'HHL', 'MMKJL', 'TPC', 'BHL',
       'PPL', 'SPC', 'SGHC', 'AHL', 'PHCL', 'SMH', 'MHCL', 'SIKLES',
       'GVL', 'MAKAR', 'BGWT', 'MEL', 'MSHL', 'IHL', 'SMHL', 'MKHL',
       'SMJC', 'RAWA', 'RIDI', 'DOLTI', 'MCHL', 'ULHC', 'CKHL', 'MANDU',
       'MEHL', 'VLUCL', 'KBSH', 'CIT', 'HIDCL', 'CHDC', 'ENL', 'NIFRA',
       'NRN', 'HATHY', 'RJBCL', 'NLICL', 'NLIC', 'LICN', 'ALICL', 'ILI',
       'RNLI', 'SNLI', 'CLI', 'SJLIC', 'HLI', 'SRLI', 'PMLI', 'BNL',
       'NLO', 'BNT', 'UNL', 'SRS', 'HDL', 'SHIVM', 'SARBTM', 'SONA',
       'GCIL', 'NUBL', 'CBBL', 'DDBL', 'SWBBL', 'FMDBL', 'SKBBL', 'SLBBL',
       'KMCDB', 'JSLBB', 'MLBBL', 'LLBS', 'HLBSL', 'VLBS', 'FOWAD',
       'MERO', 'GILB', 'RSDC', 'NMBMF', 'GBLBS', 'SMATA', 'MSLB', 'SLBSL',
       'NADEP', 'SMB', 'GMFBS', 'ALBSL', 'ILBS', 'SMFBS', 'GLBSL',
       'NICLBSL', 'MLBS', 'MLBSL', 'JBLB', 'SAMAJ', 'SHLB', 'ULBSL',
       'NESDO', 'USLB', 'UNLB', 'DLBS', 'ANLB', 'CYCL', 'AVYAN', 'ACLBSL',
       'WNLB', 'SWMF', 'NMLBBL', 'NMFBS', 'SMPDA', 'MATRI', 'NIBSF1',
       'GIMES1', 'NMBHF1', 'NEF', 'NIBLPF', 'LEMF', 'SEF', 'GIBF1',
       'CMF1', 'SAEF', 'NICGF', 'NICBF', 'SIGS2', 'CMF2', 'NBF2', 'NMB50',
       'LUK', 'SFMF', 'SLCF', 'KEF', 'NICSF', 'NIBSF2', 'SBCF', 'PSF',
       'RMF1', 'MMF1', 'KDBY', 'SIGS3', 'SAGF', 'NSIF2', 'NICFC', 'NBF3',
       'PRSF', 'NIBLGF', 'SFEF', 'C30MF', 'NICGF2', 'LVF2', 'RMF2', 'KSY',
       'NIBLSTF', 'NIBLSF', 'H8020', 'NICL', 'NIL', 'SICL', 'NLG', 'RBCL',
       'PRIN', 'HEI', 'SGIC', 'SPIL', 'SALICO', 'IGI', 'UAIL', 'NFD',
       'NTC', 'NRIC', 'HRL', 'MKCL', 'NWCL', 'NRM', 'STC', 'BBC'],
      dtype=object)